AQPLife/AQPLife/urls.py
from django.contrib import admin
from django.urls import path,include	

urlpatterns = [
    path('admin/', admin.site.urls),
    path('eventos/',include('eventos.urls')),
    path('documentacion/',include('documentacion.urls')),
]

AQPLife/eventos/urls.py
#Esta seccion de codigo se encarga de enlazar los accesos de interfaz con los controladores
# cada controlador consta de la funcion .as_view() que se encarga de llamarlos
# la variable name asocia la especificacion con los controladores



from django.urls import path
from . import views
app_name='eventos'
urlpatterns = [
	path('',views.IndexView.as_view(),name='index_2'),
	path('<int:user_id>/gestionar_evento', views.Gestionar_EventoDetailView.as_view(),name='gestionar_evento'),
	path('<int:evento_id>/evento',views.EventoDetailView.as_view(),name='evento'),
	path('<int:evento_id>/modificar_evento',views.ModificarEventoDetailView.as_view(),name='modificar_evento'),
	path('<int:user_id>/crear_evento',views.CrearEventoDetailView.as_view(), name='crear_evento'),
	path('<int:evento_id>/gestionar_actividad',views.Gestionar_ActividadDetailView.as_view(),name='gestionar_actividad'),
	path('<int:evento_id>/gestionar_ambiente',views.Gestionar_AmbienteDetailView.as_view(),name='gestionar_ambiente'),
	path('<int:evento_id>/gestionar_material',views.Gestionar_MaterialDetailView.as_view(),name='gestionar_material'),
	path('<int:evento_id>/gestionar_paquete',views.Gestionar_PaqueteDetailView.as_view(),name='gestionar_paquete'),
	path('<int:evento_id>/ver_evento',views.Ver_EventoDetailView.as_view(),name='ver_evento'),
	path('<int:evento_id>/pre_inscribirse',views.Pre_InscribirseDetailView.as_view(),name='pre_inscribirse'),
	path('<int:evento_id>/gestionar_personal',views.Gestionar_PersonalDetailView.as_view(),name='gestionar_personal'),
	path('<int:evento_id>/inscribirse',views.InscribirseDetailView.as_view(),name='inscribirse'),
	path('<int:evento_id>/gestionar_asistencia',views.Gestionar_AsistenciaDetailView.as_view(),name='gestionar_asistencia'),
	path('<int:evento_id>/gestionar_expositor',views.Gestionar_ExpositorDetailView.as_view(),name='gestionar_expositor'),
 	path('<int:evento_id>/gestionar_preinscrito',views.Gestionar_PreInscritoDetailView.as_view(),name='gestionar_preinscrito'),
 	path('<int:evento_id>/gestionar_inscrito',views.Gestionar_InscritoDetailView.as_view(),name='gestionar_inscrito'),
 	path('<int:evento_id>/eventos_inscrito',views.EventosInscritoView.as_view(),name='eventos_inscrito'),

]

AQPLife/eventos/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import datetime, date, time
import random

class Profile(models.Model):
	user 				= models.OneToOneField(User, on_delete=models.CASCADE)
	tipo_idenficacion	= models.CharField(max_length=30)
	identificacion		= models.IntegerField(default=0)

	def __str__(self):
		return str(self.user.get_username())

class Evento(models.Model):
	nombre				=models.CharField(unique=True,max_length=30)
	tipo_evento			=models.CharField(max_length=20)
	fecha_inicio		=models.DateField(default=date.today)
	fecha_fin			=models.DateField(default=date.today)
	def __str__(self):
		return self.nombre

class CategoriaPersonal(models.Model):
	evento 				=models.ForeignKey(Evento,on_delete=models.CASCADE, null=True)
	evento 				=models.ManyToManyField(Evento)
	nombre_categoria	=models.CharField(max_length=20)
	nivel_categoria		=models.IntegerField(default=1)
	def __str__(self):
		return self.nombre_categoria


class Personal(models.Model):
	evento 				=models.ForeignKey(Evento,on_delete=models.CASCADE)
	profile 			=models.ForeignKey(Profile,on_delete=models.CASCADE)
	categoria_personal	=models.ForeignKey(CategoriaPersonal,on_delete=models.CASCADE)
	def __str__(self):
		return str(self.categoria_personal)+str(" ")+str(self.evento.nombre)


class Ambiente(models.Model):
	nombre				=models.CharField(primary_key=True,max_length=30)
	evento				=models.ForeignKey(Evento,on_delete=models.CASCADE)
	ubicacion			=models.CharField(max_length=30)
	capacidad			=models.IntegerField(default=0)
	def __str__(self):
		return self.nombre

class Actividad(models.Model):	
	evento 				=models.ForeignKey(Evento,on_delete=models.CASCADE)
	ambiente  			=models.ForeignKey(Ambiente,blank=True,on_delete=models.CASCADE)
	nombre				=models.CharField(unique=True,max_length=20)
	fecha 				=models.DateField(default=date.today)
	hora_inicio			=models.TimeField(blank=True)
	hora_fin			=models.TimeField(blank=True)
	def __str__(self):
		return self.nombre

class MaterialActividad(models.Model):
	actividad 			=models.ForeignKey(Actividad,on_delete=models.CASCADE)
	nombre 				=models.CharField(unique=True,max_length=20)
	cantidad 			=models.IntegerField(default=0)
	stock				=models.IntegerField(default=0)
	def __str__(self):
		return self.nombre

class MaterialAmbiente(models.Model):
	ambiente 			=models.ForeignKey(Ambiente,on_delete=models.CASCADE)
	nombre 				=models.CharField(unique=True,max_length=20)
	cantidad			=models.IntegerField(default=0)
	stock 				=models.IntegerField(default=0)
	def __str__(self):
		return self.nombre

class Paquete(models.Model):
	evento 				=models.ForeignKey(Evento,on_delete=models.CASCADE)
	nombre 				=models.CharField(max_length=30)
	descripcion			=models.CharField(max_length=100)
	costo				=models.FloatField(default=0)
	actividad 			=models.ManyToManyField(Actividad)
	def __str__(self):
		return self.nombre

class Transaccion(models.Model):
	transaccion_opciones=[
		('compra','Compra'),
		('venta','Venta'),
	]
	opciones_estado=[
		('aprobado','Aprobado'),
		('proceso','En proceso'),
	]
	evento 				=models.ForeignKey(Evento,on_delete=models.CASCADE)
	numero_factura		=models.CharField(max_length=30)
	motivo				=models.CharField(max_length=100)
	cantidad			=models.FloatField(default=0)
	tipo_transaccion 	=models.CharField(choices=transaccion_opciones,default='compra',max_length=10)
	estado_transaccion	=models.CharField(choices=opciones_estado,default='proceso',max_length=10)
	fecha 				=models.DateField(default=date.today)
	def __str__(self):
		return self.numero_factura


class Inscrito(models.Model):
	inscripcion_opciones=[
		(False,'Pre-Inscrito'),
		(True,'Inscrito'),
	]
	profile 			=models.ForeignKey(Profile,on_delete=models.CASCADE)
	evento 				=models.ForeignKey(Evento,on_delete=models.CASCADE)
	paquete				=models.ForeignKey(Paquete,on_delete=models.CASCADE)
	codigo_inscripcion	=models.IntegerField(default=random.randint(1000000,5000000))
	estado_inscripcion 	=models.BooleanField(choices=inscripcion_opciones,default=False)
	def __str__(self):
		return self.profile.user.username


#vestigio, listo para borrar!		
class PaqueteActividad(models.Model):
	id_paquete			=models.ForeignKey(Paquete,on_delete=models.CASCADE)
	id_actividad		=models.ForeignKey(Actividad,on_delete=models.CASCADE)



class Expositor(models.Model):
	nombre 				=models.CharField(max_length=20)
	apellido 			=models.CharField(max_length=30)
	actividad 			=models.ManyToManyField(Actividad)
	def __str__(self):
		return self.nombre



class Asistencia(models.Model):
	opciones_asistencia=[
		('general','General'),
		('actividad','Actividad')
	]
	tipo_asistencia 	=models.CharField(choices=opciones_asistencia,default='general', max_length=15 )
	inscrito 			=models.ForeignKey(Inscrito,on_delete=models.CASCADE)
	actividad 			=models.ForeignKey(Actividad,on_delete=models.CASCADE, blank=True)
	fecha  				=models.DateField(default=date.today)
	hora 				=models.TimeField(default=datetime.now().time())
	def __str__(self):
		return self.inscrito


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

AQPLife/eventos/forms.py
from django import forms
from .models import *


#Aqui se encuentran los forms que alteran directamente la base de datos
#Para mas informacion revisar la documentacion de Django.


class CrearEventoForm(forms.ModelForm):
	class Meta:
		model=Evento
		fields=[
			'nombre',
			'tipo_evento',
			'fecha_inicio',
			'fecha_fin'
		]
		widgets={
			'nombre':forms.TextInput(attrs={'class':'input'}),
			'tipo_evento':forms.TextInput(attrs={'class':'input'}),
			'fecha_inicio':forms.TextInput(attrs={'type':'text','class':'datepicker'}),
			'fecha_fin':forms.TextInput(attrs={'type':'text','class':'datepicker'})
		}
class CrearAmbienteForm(forms.ModelForm):
	class Meta:
		model=Ambiente
		fields=[
			'evento',
			'nombre',
			'ubicacion',
			'capacidad'
		]
		widgets={
			'evento':forms.TextInput(attrs={'class':'input', 'style':'display:none' ,'type':'hidden'	}),
			'nombre':forms.TextInput(attrs={'class':'input'}),
			'ubicacion':forms.TextInput(attrs={'class':'input'}),
			'capacidad':forms.NumberInput(attrs={'class':'input'})
		}


class ModificarEventoForm(forms.ModelForm):
	class Meta:
		model=Evento
		fields=[
			'nombre',
			'tipo_evento',
			'fecha_inicio',
			'fecha_fin'
		]
		widgets={
			'nombre':forms.TextInput(attrs={'class':'input'}),
			'tipo_evento':forms.TextInput(attrs={'class':'input'}),
			'fecha_inicio':forms.TextInput(attrs={'type':'text','class':'datepicker'}),
			'fecha_fin':forms.TextInput(attrs={'type':'text','class':'datepicker'})
		}
class CrearAmbienteForm(forms.ModelForm):
	class Meta:
		model=Ambiente
		fields=[
			'evento',
			'nombre',
			'ubicacion',
			'capacidad'
		]
		widgets={
			'evento':forms.TextInput(attrs={'class':'input', 'style':'display:none' ,'type':'hidden'	}),
			'nombre':forms.TextInput(attrs={'class':'input'}),
			'ubicacion':forms.TextInput(attrs={'class':'input'}),
			'capacidad':forms.NumberInput(attrs={'class':'input'})
		}


class CrearActividadForm(forms.ModelForm):
	class Meta:
		model=Actividad
		fields=[
			'evento',
			'ambiente',
			'nombre',
			'fecha',
			'hora_inicio',
			'hora_fin'
		]
		widgets={
			'evento':forms.TextInput(attrs={'class':'input ', 'style':'display:none' ,'type':'hidden'}),
			'ambiente':forms.TextInput(attrs={'class':'autocomplete input-field','type':'text', 'id':'autocomplete-input'}),
			'nombre':forms.TextInput(attrs={'class':'input'}),
			'fecha':forms.TextInput(attrs={'type':'text','class':'datepicker'}),
			'hora_inicio':forms.TextInput(attrs={'type':'text','class':'timepicker'}),
			'hora_fin':forms.TextInput(attrs={'type':'text','class':'timepicker'})
		}

class CrearPaqueteForm(forms.ModelForm):
	actividad			= forms.ModelMultipleChoiceField(queryset = Actividad.objects.all())

	
	class Meta:
		model=Paquete
		fields=[
				'evento',
				'nombre',
				'costo',
				'actividad',
				'descripcion'
				
			]
		widgets={
			'evento':forms.TextInput(attrs={'class':'input ', 'style':'display:none' ,'type':'hidden'}),
			
		}
	def __init__(self,*args,**kwargs):
		evento=kwargs.pop('instance_evento',None)
		super(CrearPaqueteForm, self).__init__(*args, **kwargs)
		if evento:
			self.fields['evento'].initial=evento.id
			self.fields['actividad'] = forms.ModelMultipleChoiceField(queryset=Actividad.objects.filter(evento=evento.id))

class CrearPersonalForm(forms.ModelForm):
	categoria_personal 		=forms.ModelMultipleChoiceField(queryset=CategoriaPersonal.objects.all())
	class Meta:
		model=Personal
		fields=[
			'evento',
			'profile',
			'categoria_personal'
		]
		widgets={
			'evento':forms.TextInput(attrs={'class':'input ', 'style':'display:none' ,'type':'hidden'}),
				
		}
	def __init__(self,*args,**kwargs):
		evento=kwargs.pop('instance_evento',None)
		super(CrearPersonalForm, self).__init__(*args, **kwargs)
		if evento:
			self.fields['evento'].initial=evento.id


class PreInscribirseForm(forms.ModelForm):
	paquete = forms.ModelChoiceField(queryset=Paquete.objects.all())
	class Meta:
		model=Inscrito
		fields=[
			'profile',
			'evento',
			'paquete',
			'codigo_inscripcion',
			'estado_inscripcion'
		]
		widgets={
			'profile':forms.TextInput(attrs={'class':'input ', 'style':'display:none' ,'type':'hidden'}),
			'evento':forms.TextInput(attrs={'class':'input ', 'style':'display:none' ,'type':'hidden'}),	
			'estado_inscripcion':forms.TextInput(attrs={'class':'input ', 'style':'display:none' ,'type':'hidden'}),
		}
	def __init__(self,*args,**kwargs):
		evento=kwargs.pop('instance_evento',None)
		profile=kwargs.pop('instace_profile',None)
		super(PreInscribirseForm, self).__init__(*args, **kwargs)
		if evento:
			self.fields['profile'].initial				=profile.user
			self.fields['evento'].initial				=evento.id
			self.fields['estado_inscripcion'].initial	=False
			self.fields['paquete'] 						= forms.ModelChoiceField(queryset=Paquete.objects.filter(evento=evento.id))

class MaterialActividadForm(forms.ModelForm):
	paquete = forms.ModelChoiceField(queryset=Paquete.objects.all())
	class Meta:
		model=Inscrito
		fields='__all__'

class CrearExpositorForm(forms.ModelForm):	
	actividad			= forms.ModelMultipleChoiceField(queryset = Actividad.objects.all())

	
	class Meta:
		model=Expositor
		fields=[
				'nombre',
				'apellido',
				'actividad'
			]
	def __init__(self,*args,**kwargs):
		evento=kwargs.pop('instance_evento',None)
		super(CrearExpositorForm, self).__init__(*args, **kwargs)
		if evento:
			self.fields['actividad'] = forms.ModelMultipleChoiceField(queryset=Actividad.objects.filter(evento=evento.id))

AQPLife/eventos/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from .forms import *
# Create your views here.
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render,redirect
from django.views import View
from django.views.generic.detail import DetailView
from .views_vista_usuario import *
from .views_modulo_configuracion import *

AQPLife/eventos/templates/eventos/eventos_inscrito.html
{%extends 'eventos/index.html'%}
{% load static %}

{%block title%}Eventos Inscrito{%endblock%}


{%block eventos_list%}
	
			{%for inscrito in list_inscritos%}
				<div class="carousel-item black-text contenedor_carousel" >
					<img src="{%static 'eventos/images/evento_logo.png'%}" style="width:50%;">
					<div class="texto_carousel">
					<h2 class="flow-text black-text"><a href="{%url 'eventos:ver_evento' inscrito.evento.id%}">{{inscrito.evento.nombre}}</a></h2>
					<p class="flow-text black-text">{{inscrito.evento.tipo_evento}}</p>
						
					</div>
					
				</div>
			{%endfor%}
{%endblock%}

AQPLife/eventos/templates/eventos/gestionar_evento.html
{%extends 'eventos/index.html'%}
{% load static %}

{%block title%}Gestionar Eventos{%endblock%}


{%block eventos_list%}
	
			{%for personal in object.personal_set.all%}
				<div class="carousel-item black-text contenedor_carousel" >
					<img src="{%static 'eventos/images/evento_logo.png'%}" style="width:50%;">
					<div class="texto_carousel">
					<h2 class="flow-text black-text"><a href="{%url 'eventos:evento' personal.evento.id%}">{{personal.evento.nombre}}</a></h2>
					<p class="flow-text black-text">{{personal.evento.tipo_evento}}</p>
						
					</div>
					
				</div>
			{%endfor%}
{%endblock%} 
<!--asdasdasdasasdasdsad -->

AQPLife/eventos/templates/eventos/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{%block title%}Plataforma Eventos {%endblock%}</title>
	
	{% block header %}

		<link rel="stylesheet" type="text/css" href="{% static 'eventos/css/materialize.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'eventos/style.css' %}">
		
		<link rel="stylesheet" href="{% static 'eventos/icons.css' %}">
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	{% endblock %}


</head>
<body>
	{%block sidenav%}
		<ul id="slide-out" class="sidenav">
			<li><div class="user-view">
				<div class="background teal lighten-2">
			
				</div>
				<a href="#user"><i class="medium material-icons index">account_circle</i></a>
				<a href="#name"><span class="white-text name">{{user.username}}</span></a>
				<a href="#email"><span class="white-text email">{{user.email}}</span></a>
				</div>
			</li>
			<li><a href="{%url 'eventos:gestionar_evento' user.id %}"><i class="material-icons index">assignment_ind</i>Mis eventos</a></li>
			<li><a href=""><i class="material-icons index">exit_to_app</i> Cerrar Sesión</a></li>
			<li><div class="divider"></div></li>
			<li><a class="subheader">Editar Datos</a></li>
			<li><a class="waves-effect" href="{%url 'admin:auth_user_change' user.id%}">Modificar Informacion</a></li>
			<li><a href="{%url 'admin:password_change'%}">Cambiar Contraseña</a></li>

		</ul>
	
	{%endblock%}




	{% block nav%}
	<!-- Dropdown Structure -->
	<ul id="dropdown-MisEventos" class="dropdown-content">
	<li><a href="{%url 'eventos:gestionar_evento' user.id %}">Creados</a></li>
	<li class="divider"></li>
	<li><a href="{%url 'eventos:eventos_inscrito' user.id %}">Inscritos</a></li>
	</ul>
	<!-- Dropdown Structure -->
		<nav>

		<div class="nav-wrapper este"  id="nav_bar">
		  <a href="{%url 'eventos:index_2'%}" class=" brand-logo">Make Events</a>
		  <ul id="nav-mobile" class="right hide-on-med-and-down">

		  	<!-- Dropdown Trigger -->
		    <li><a class="dropdown-trigger" href="#!" data-target="dropdown-MisEventos">Mis Eventos</a></li>
		    <!-- Dropdown Trigger -->	

		    <li><a href="">Contactanos</a></li>
		    <li><a href="#" data-target="slide-out" class="sidenav-trigger show-on-large"><i class="material-icons index right">account_circle</i>{{user}}</a></li>

		  </ul>
		</div>

		</nav>
    {%endblock%}

	{%block section_1%}
	<div class="section ">
		
		<div class="carousel carousel-slider center">
			<!--<div class="carousel-fixed-item center">
				<a class="btn waves-effect white grey-text darken-text-2">button</a>
			</div>-->
			{%block eventos_list%}

			{%for evento in eventos_list%}
				<div class="carousel-item black-text contenedor_carousel" >
					<img src="{%static 'eventos/images/evento_logo.png'%}" style="width:50%;">
					
					<div class="texto_carousel">
					<h2 class="flow-text black-text"><a href="{%url 'eventos:ver_evento' evento.id%}">{{evento.nombre}}</a></h2>
					<p class="flow-text black-text">{{evento.tipo_evento}}</p>
						
					</div>
					
				</div>
			{%endfor%}

			{%endblock%}
		</div>
	</div>
		
	{%endblock%}
	<div class="divider"></div>
	{%block section_2%}
	<div class="section container row">
		<div class="col center s4">
			
			<div class="card">
				<div class="card-image">
					
					<!--Click Crear Evento-->

					<img src="{%static 'eventos/images/crear_evento.png'%}">
					<span class="card-title">Crear Evento</span>
					<a href="{%url 'eventos:crear_evento' user.id%}" class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons index">add</i></a>
					</div>
					<div class="card-content">
					<p>Crea tu propio evento de manera rapida, sencilla y ¡gratis!. No pierdas tiempo y unete a la plataforma MakeEvents.</p>
				</div>
			</div>

		</div>
		<div class="col center s4">
			
			<div class="card">
				<div class="card-image">
					<img src="{%static 'eventos/images/eventos.png'%}">
					<span class="card-title">Eventos Disponibles</span>
					<a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons index">search</i></a>
					</div>
					<div class="card-content">
					<p>Interactua con los miles de eventos que MakeEvents tiene para ti . ¡Animate y compra tu paquete ya!.</p>
				</div>
			</div>

		</div>
		<div class="col center s4">
			
			<div class="card">
				<div class="card-image">
					<img src="{%static 'eventos/images/soporte.jpg'%}">
					<span class="card-title">Soporte para Administradores</span>
					<a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons index">assignment_ind</i></a>
					</div>
					<div class="card-content">
					<p>¿Ya tienes tu evento?. Te ayudamos a mejorarlo y que superes tu meta de participación. MakeEvents esta para ti. </p>
				</div>
			</div>

		</div>
		
  	</div>
	{%endblock%}
		<div class="divider"></div>
	{%block section_3%}	
	    <footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Make Events</h5>
                <p class="grey-text text-lighten-4">Derechos Reservados</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Enlaces Rapidos</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Contactanos</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Documentacion</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Ayuda</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Servicios</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2019 Derechos AqpLife-Arequipa-Peru
            <a class="grey-text text-lighten-4 right" href="#!">IS2</a>
            </div>
          </div>
        </footer>
	

	{%endblock%}

	<script type="text/javascript" src="{% static 'eventos/js/jquery-2.1.1.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'eventos/js/materialize.min.js' %}"></script>

	 {%block scrip_text%}
		<script type="text/javascript">
			

			$(document).ready(function(){
					$(".dropdown-trigger").dropdown();
    				$('.sidenav').sidenav();
    				$('.tabs').tabs();
    				$('.carousel.carousel-slider').carousel({
		    			fullWidth: true,
		    			indicators: true
		      			});

    						});
        	
 
			
  						

		</script>
		{%endblock%}		
</body>
</html>

AQPLife/eventos/templates/eventos/modificar_evento.html
{%extends 'eventos/index.html'%}

{%block title%}Modificar Evento{%endblock%}

{%block section_1%}
	<div class="section container row">
		<h2> Modificar Datos </h2>
			
				<form action="" method="post">
		    {% csrf_token %}
		    {{ form.as_p }}
		    <input type="submit" value="Modificar">
		</form>
				
	</div>
{%endblock%}

{%block scrip_text%}
    <script type="text/javascript">
        $(document).ready(function(){
                    $('.datepicker').datepicker({
                format:'yyyy-mm-dd',
                
            });
                    $(".dropdown-trigger").dropdown();
                      $('.tooltipped').tooltip();
                    $('.sidenav').sidenav();
                    $('.tabs').tabs();
                    $('.modal').modal();
                    $('.collapsible').collapsible();
                    $('select').formSelect();
                    });
    </script>
    
{%endblock%}

AQPLife/eventos/templates/eventos/ver_evento.html
{%extends 'eventos/index.html'%}

{%block title%}Evento: {{evento.nombre}}{%endblock%}

{%block section_1%}
	<div class="section container row">
		<div class="col s12 center-align">
			<h2> {{evento.nombre}}</h2>
		</div>

		<div class="col s6 left-align">
			
			<ul class="collection with-header collapsible ">
				<li class="collection-header"><h6><b>Descripción</b></h6></li>

				<li class="collection-item"><div>Inicio	: {{evento.fecha_inicio}}<a href="#!" class="secondary-content"><i class="material-icons">date_range</i></a></div></li>
				<li class="collection-item"><div>Fin 	: {{evento.fecha_fin}}<a href="#!" class="secondary-content"><i class="material-icons">date_range</i></a></div></li>
				<li class="collection-header"><h6><b>Actividades</b></h6></li>
					{%for actividad in evento.actividad_set.all%}
						<li >

							<div class="collapsible-header collection-item">{{actividad.nombre}}
							
							</div>
							<div class="collapsible-body row">
								<div class="col s6">
										<ul>
									<li>Fecha: {{actividad.fecha}}</li>
									<li>Ambiente: {{actividad.ambiente}}</li>
									<li>Inicio: {{actividad.hora_inicio}} - Fin: {{actividad.hora_fin}} </li>
									
									</ul>	
								</div>
								<div class="col s6">
									<ul>
										<li>Expositores</li>
										{%for expositor in actividad.expositor_set.all%}
												<li>-{{expositor.apellido}}, {{expositor.nombre}}</li>
										{%endfor%}
									
								</ul>
								</div>

								
							</div>
						</li>
					{%endfor%}
			
			</ul>	

		</div>
		<div class="row col s6 center-align  ">
			<div class="section col s12">
					<img class="col s12"  src="https://materializecss.com/images/sample-1.jpg">
				
			</div>
			<div class="divider col s12"></div>

			<div class="section col s12">
				<ul>
				<li><a href="{%url 'eventos:pre_inscribirse' evento.id%}" class="waves-effect waves-light btn">Pre-Inscribirse</a> 
					<a href="{%url 'eventos:inscribirse' evento.id%}" class="waves-effect waves-light btn">Inscribirse</a></li>
				
				</ul>
			</div>
			<div class="divider col s12"></div>
			<div class="section col s12">
        
			</div>
					
		</div>
		
	</div>
{%endblock%}



{%block scrip_text%}
	<script type="text/javascript">
		$(document).ready(function(){
					$(".dropdown-trigger").dropdown();
    				$('.sidenav').sidenav();
    				$('.tabs').tabs();
    				$('.modal').modal();
    				$('.collapsible').collapsible();
    				});
	</script>
	
{%endblock%}